### ISSUE TITLE
Black screen on video player fragment. Just audio

### ISSUE THREAD

**Issue by reeq-dev** [kaltura/kaltura-player-android#129]
Following demo from this source i've implemented player but got a black screen with audio only for fragment player.

https://bitbucket.org/sukdev/kaltura-android-sdk/src/master/KalturaDemos/PlayerFragmentDemo/src/main/java/com/kaltura/kalturaplayerfragmentdemo/PlayerFragment.java

```
ext {
    buildToolsVersion = "29.0.3"
    minSdkVersion = 21
    compileSdkVersion = 29
}
```

```
maven {
    url("https://api.bitbucket.org/2.0/repositories/sukdev/kaltura-android-sdk/src/releases")
}
```

```
implementation 'com.kaltura.player:tvplayer:4.15.0'
implementation 'com.streamamg:playersdk:2.7.3'
```

**Comment by GouravSna** [comment]
Try our AudioOnly sample https://github.com/kaltura/kaltura-player-android-samples/tree/develop/BasicSamples/AudioOnlyBasicSetup. You can replace your stream URL and check if there is some issue on Player.

Please let us know your findings.

**Comment by reeq-dev** [comment]
@GouravSna, hi and thanks for quick reply. I did not get why do i need to setup AudioOnly player when the issue is about black screen. Audio is working just fine, but i dont have a video.

![image](https://user-images.githubusercontent.com/26365596/127141999-45032070-2798-49ce-b5f9-da66867c46c2.png)

![image](https://user-images.githubusercontent.com/26365596/127141612-c4049c5d-4ddd-44a4-9e2d-bb76d0fdd9b8.png)

**Comment by GouravSna** [comment]
Oh ok. I thought another way with audio only content.
So try our https://github.com/kaltura/kaltura-player-android-samples/tree/develop/BasicSamples/BasicSetup sample, here you can pass the media URL. 

Do you see this issue only with one content ? Did you try playing this content on other device ? Do you see any exception in logcat ? It could be an issue with decoders as well.

**Comment by kaltura-hooks** [comment]
Hi @Noolie,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by reeq-dev** [comment]
> Do you see this issue only with one content ?

 No, all entryIds give the same result.

> Did you try playing this content on other device ?

 Nope, just android for now. But i'll ask our sales if they have some web version and check it later.
 

> Do you see any exception in logcat ? 

Only one error appears on initialising player and it seems does nt make any sense for our case i think:

`2021-07-27 14:08:42.166 27157-27157 E/PlayerFragment: KPlayer onKPlayerError WebViewError:404-https://HOSTING/files/design/mobile2016/images/logo.png-`

Will try basic player setup and will return with a result

**Comment by GouravSna** [comment]
Hi @Noolie , 

I can see that you are using our [deprecated player](https://github.com/kaltura/player-sdk-native-android/blob/master/README.md).

If you are using our BE and our customer then please reach out to us internally.
In case, if you are not and trying to use our player with media url then try our [basic sample](https://github.com/kaltura/kaltura-player-android-samples/tree/master/BasicSamples/BasicSetup).

In case, if nothing works; please send us an email on qafront1@gmail.com.

If you want to try our demos with Fragments then you can try this [sample](https://github.com/kaltura/kaltura-player-android-samples/tree/master/AdvancedSamples/FullDemo) and run FullDemo module.

**Comment by reeq-dev** [comment]
Well i could not setup the player properly, even basic. Since we are using java and react-native bridge it's quite complicated and time wasted to setup even for test purposes. Found another solution to deliver videos for default android/ios player by making a video as mp4/3gp etc. This tool http://player.kaltura.com/docs/getSources set my mind for this decision.
Issue can be closed since bug was created for "deprecated player".

**Comment by GouravSna** [comment]
Please take a look at this dev portal https://developer.kaltura.com/player/. 
http://player.kaltura.com/docs/getSources this tool is also part of deprecated web player.
