### ISSUE TITLE
Different player uses - ott, ovp, basic

### ISSUE THREAD

**Issue by wishygupta** [kaltura/kaltura-player-android#156]
What is the diffrence between these 3 players and what additional features does each give.
1 . OTT
2 . OVP - as I understand the videos are hosted on Kaltura for this
3. Basic - doesn't require partner ID and can be used as standalone

My question is on OTT vs OVP player?

**Comment by kaltura-hooks** [comment]
Hi @wishygupta,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GouravSna** [comment]
@wishygupta , Actually this is related to the setup of Kaltura developer account.
If you are a Kaltura client, I will suggest you talk to Account Manager or CSM.
