### ISSUE TITLE
下载后编译有报错，无法应用com.android.library

### ISSUE THREAD

**Issue by weisx-0904** [kaltura/kaltura-player-android#82]
下载后编译有报错，无法应用com.android.library
![image](https://user-images.githubusercontent.com/65340680/82418445-97812900-9aaf-11ea-8943-7adfff9e51c3.png)

**Comment by kaltura-hooks** [comment]
Hi @weisx-0904,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GouravSna** [comment]
Hi @weisx-0904 , Please try to do clean and build or try to upgrade the gradle version (if required) . We don't see any issues in our end.

**Comment by GouravSna** [comment]
@weisx-0904 , do you still see any issue while building?

**Comment by GouravSna** [comment]
No more details so closing this.
